### ISSUE TITLE
Add support for listing real apps instead of everything in $PATH

### ISSUE THREAD

**Issue by TheLastProject** [Pext/pext_module_launcher#2]
This should become the new default, especially on non-Linux

**Comment by TheLastProject** [comment]
For macOS this was added in fb5cdd80141adf348e674103aa919625a6c182a8. Linux and Windows still remain

**Comment by ata2001** [comment]
I started working on adding support for desktop entries on Linux.

Todo:
- [ ] Parse desktop files and list apps
- [ ] Display localized name of apps
- [ ] Handle arguments

**Comment by TheLastProject** [comment]
For displaying localized names, it'll probably be helpful to check settings['_locale'] that the module gets from Pext. It contains the locale Pext is in, so you don't have to do locale detection yourself.

**Comment by TheLastProject** [comment]
Superseded by #6.
