### ISSUE TITLE
Missing module "win32com"

### ISSUE THREAD

**Issue by TangentFoxy** [Pext/pext_module_launcher#7]
On Windows 10, attempting to use App Launcher with default option produces the error "No Module named 'win32com'.":

![image](https://user-images.githubusercontent.com/15093567/67632598-b0e82c80-f862-11e9-901d-b6262c15acc8.png)

- OS: Windows 10
- Pext v0.26-27-g044fc99
- App Launcher version: g9834d00 (2019-10-17 11:24:45)

**Comment by TheLastProject** [comment]
Nice find. A quick web search seems to state that win32com is part of pywin32. So pywin32 should be added to requirements.txt. Looking on https://pypi.org/project/pywin32/, the latest version is 225, so let's pin it on that in requirements.txt.
